### ISSUE TITLE
When switching between the mutant and test tabs multiple requests are executed

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-dashboard#270] opened 2023-03-15 09:33 UTC
## Problem

For example, this is me switching between tabs 2 times:

![image](https://user-images.githubusercontent.com/34238405/225266416-05c80fa8-a20b-4114-a6ed-0a6fdd918d6e.png)

## Steps to reproduce

1. Visit the [Dashboard](https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/stryker-js/master).
2. Switch from `mutant`  to `test` view.
3. Observe multiple requests in the developer console.

## Misc

- Tested on Firefox and Edge (newest versions).
- It appears that on page load two of the same requests are executed.
- Also I noticed that this happens when the fragment gets updated (changed to gibberish: `#bla123`, does a request as well) 

## Solution

Only do the GET request once 👍.

potentially something in the Router:
https://github.com/stryker-mutator/stryker-dashboard/blob/472efcf03d22d349cd3bbf704d2b38001a5fb1ae/packages/website-frontend/src/app/app-router.module.ts#L17

**Comment by nicojs** [comment] 2023-03-15 09:38
Thanks @xandervedder, for this thorough report 💙

I think the issue is with the `ReportPageComponent`. It probably can be fixed with a simple [`distinctUntilChanged` rxjs operator](https://www.learnrxjs.io/learn-rxjs/operators/filtering/distinctuntilchanged)
https://github.com/stryker-mutator/stryker-dashboard/blob/472efcf03d22d349cd3bbf704d2b38001a5fb1ae/packages/website-frontend/src/app/report/report-page/report-page.component.ts#L62

**Closed** 2023-05-12 08:17 UTC
Labels: bug
